---
title: Fridei
timezone: America/Toronto
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
- scope:
    path: ''
  values:
    layout: page
author: et6 - at8
navbar-links:
  About Me: aboutme
  Resources:
  - Sundei: http://sundei.nhungngaycuoituan.com
  - Weekends: http://nhungngaycuoituan.com
  Author's home: http://nhungngaycuoituan.com
avatar: https://ucc1d78e12f3634dda28e551244d.previews.dropboxusercontent.com/p/thumb/ABIrnSoAY5WwaDufl7PrGnj9GEtsiCokSHrclrZcTz3H-J3htwwtQmsa5xeOcBXdV_v5lRmd48HSfvn7z040sx7UIGIvlBtN1faTqZ0dLRj7V7Gp__c3bU2KDigrmEm7BhIdZ7xecmSJCuqWdEQf4LzsbaLx8rHmRueGjwiSOQkkrGzzibpbTgvDfKWnyf3XW2yZEKT1s5eaL37Bye0Ilu5XxWqm55SGAhzja3ix5MaOqf6qLz2Fsucl-6YXj5OqUyjRbdmIA-79-evB1atBXWmZtWt68Eja7pRkawDabls2oBngqvDirLMvwRrqANKv1bcxMhosU5Z8bSzdvAx4WSfsm0LB3bA30imxnc2GP3K2RA/p.png?fv_content=true&size_mode=5
round-avatar: true
social-network-links:
  email: someone@example.com
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: c/daattali
rss-description: This website is a virtual proof that I'm awesome
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false
url-pretty: MyWebsite.com
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
date_format: "%B %-d, %Y"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: GFM
exclude:
- CHANGELOG.md
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- screenshot.png
- docs/
plugins:
- jekyll-paginate
- jekyll-sitemap
